In [1]:
import numpy as np

In [38]:
# weights[output][input]
# weights = np.array([
#   # toes wlrec nfans
#     [0.1, 0.1, -0.3], # hurt
#     [0.1, 0.2, 0.0],  # win
#     [0.0, 1.3, 0.1],  # sad
# ]).T

# weights[input][output]
weights = np.array([
  # hurt  win  sad
    [0.1, 0.1, 0.0],  # toes
    [0.1, 0.2, 1.3],  # wlrec
    [-0.3, 0.0, 0.1], # nfans
])

# Inputs
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])
input = np.array([toes[0], wlrec[0], nfans[0]])

# Actual results
hurt = np.array([0.1, 0.0, 0.0, 0.1])
win  = np.array([  1,   1,   0,   1])
sad  = np.array([0.1, 0.0, 0.1, 0.2])
goal_pred = np.array([hurt[0], win[0], sad[0]])

# Alpha
alpha = 0.01

In [39]:
def nn(input, weights):
    return input.dot(weights)

In [40]:
iter = 0
pred = nn(input, weights)

print("Iter:", iter)
print("Prediction:", pred)
print("Weights:\n", weights)

delta = np.zeros(len(pred))
error = np.zeros(len(pred))
for i in range(len(pred)):
    delta[i] = pred[i] - goal_pred[i]
    error[i] = (pred[i] - goal_pred[i]) ** 2
print("Error:", error)
print("Deltas:", delta)

derivatives = np.outer(input, delta)
print("Derivatives:\n", derivatives)

derivatives *= alpha
weights -= derivatives
print("New weights:\n", weights)

print()


Iter: 0
Prediction: [0.555 0.98  0.965]
Weights:
 [[ 0.1  0.1  0. ]
 [ 0.1  0.2  1.3]
 [-0.3  0.   0.1]]
Error: [2.07025e-01 4.00000e-04 7.48225e-01]
Deltas: [ 0.455 -0.02   0.865]
Derivatives:
 [[ 3.8675  -0.17     7.3525 ]
 [ 0.29575 -0.013    0.56225]
 [ 0.546   -0.024    1.038  ]]
New weights:
 [[ 6.1325000e-02  1.0170000e-01 -7.3525000e-02]
 [ 9.7042500e-02  2.0013000e-01  1.2943775e+00]
 [-3.0546000e-01  2.4000000e-04  8.9620000e-02]]



In [33]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
b = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1],
])
c = a - b
print(c)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
